version: '3.8'

services:
  db:
    image: postgres:16
    container_name: platic_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: plastic_web
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 34412
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plastic_backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/plastic_web
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 34412

volumes:
  postgres_data:
